server:
  port: 0

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  application:
    name: momentours-user-service
  config:
    import:
      - classpath:/bootstrap.yml


logging:
  level:
    com:
      myhandjava:
        momentours-user: debug

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka