server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka
spring:
  config:
    import:
      - classpath:/bootstrap.yml
  application:
    name: gateway-server



  cloud:
    gateway:
      routes:

        - id: momentours-user-get
          uri: lb://MOMENTOURS-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: momentours-user-put
          uri: lb://MOMENTOURS-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=PUT
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: momentours-user-delete
          uri: lb://MOMENTOURS-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=DELETE
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: momentours-user-post
          uri: lb://MOMENTOURS-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: momentours-get
          uri: lb://MOMENTOURS-SERVICE
          predicates:
            - Path=/momentours-service/**
            - Method=GET
          filters:
            - RewritePath=/momentours-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: momentours-post
          uri: lb://MOMENTOURS-SERVICE
          predicates:
            - Path=/momentours-service/**
            - Method=POST
          filters:
            - RewritePath=/momentours-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: momentours-delete
          uri: lb://MOMENTOURS-SERVICE
          predicates:
            - Path=/momentours-service/**
            - Method=DELETE
          filters:
            - RewritePath=/momentours-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: momentours-put
          uri: lb://MOMENTOURS-SERVICE
          predicates:
            - Path=/momentours-service/**
            - Method=PUT
          filters:
            - RewritePath=/momentours-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter